### ISSUE TITLE
Add markdown presenter

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/jupyterlab-deck#19]
## Elevator Pitch

Add a basic presenter for markdown slides viewed in the Markdown Preview activity.

## Motivation

`.md` files should make fine slides. 

## Design Ideas

The specs for [markdown](https://daringfireball.net/projects/markdown/syntax#hr) and [commonmark](https://spec.commonmark.org/0.29/#thematic-break) allow for several syntaxes for horizontal rules, and these are commonly used for tools such as [marp](https://marp.app/) and others.

Without supporting _all_ the features, we can probably fiat `hr`s (written with `---`) as slides. The `~` operator can be used to select stuff between multiple as-rendered `hr` elements.

**Comment by bollwyvl** [comment]
To expand on the above, given the id of the markdown viewer widget:

Or, once the presenter gets to work
```css
body[data-jp-deck-mode="presenting"] :not(.lm-mod-hidden) .jp-MarkdownViewer > * {
  display: none;  // or equivalent
}
body[data-jp-deck-mode="presenting"] :not(.lm-mod-hidden) .jp-MarkdownViewer hr:nth-of-type(1) ~ :not(hr:nth-of-type(2) ~ *):not(hr)') {
  display: block; // or equivalent
}
```

This could be tightened up by annotating the leading `hr` element with .e.g `jp-deck-mod-onscreen`, so that the CSS isn't changing as frequently, though it will be a full repaint _anyway_ when changing the classes.
