### ISSUE TITLE
Add Tag-based Cell Styles

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/jupyterlab-deck#39]
## Elevator Pitch

Allow a Deck author to add styling via different, discoverable cell tags:

- _Hide all inputs of this cell_
- _Show the input and output side by side_

## Motivation

Despite being semantically weak, a number of ecosystem tools encourage tag use.

An author may use these tools for non-_Deck_ presentation of notebooks. These might include useful rules that can act as "base coat" choices for slide building. As a _Deck_ is closer to this kind of experience than "full" Notebook authoring, an author should be able to (temporarily) opt into a set of tag opinions, or build, save, and reuse their own.

### Why tags?

- `jupyterlab-fonts`  hoists `cell/metadata/tags` to the DOM in `data`
- the chosen system should serve both ends of the spectrum...
  - ...from highly-prescriptive values 
    - [myst cell tags](https://github.com/executablebooks/MyST-NB/blob/385c4a7afb3a377486c1aa7a86b4c8a0e93484f5/docs/configuration.md?plain=1#L121)
  - ... or just as _an_ approach
    - [voila](https://voila.readthedocs.io/en/stable/customize.html#hiding-output-and-code-cells-based-on-cell-tags)

### API Ideas
- new tag templates could be registered via the manager API
  - or via settings defaults e.g. `conf.d`
  - or via discovery of a top-level key in other extensions' settings
- tag templates can be copied from other notebooks

### UI Ideas
- in _Design Tools_, offer a _Cell Tag_ picker, offer applying a tag...
 - from the current notebooks
 - from other notebooks
 - from a pre-defined set of tags
 - from scratch in "expert" mode
   - allows for creating new selectors and property values. 

A fully-expanded view might appear like:

![untitled dio (2)](https://user-images.githubusercontent.com/45380/209034300-72bbcfd3-25ed-4dd4-aac7-6ff90756ac1a.svg)

Where, by default, the main UI is a growing list of currently in-use tags.

### Data Ideas
Per-cell tags will go in `cells/*/metadata/tags`.

Style templates will end up in `notebook/metadata/@jupyterlab/deck`, perhaps of the form

```yaml
styleTemplates:
  myst-nb:
    title: Myst-NB
    icon: |
      data:image/svg:...
    remove-inputs:
      title: Remove Outputs
      description: Show only the cell input
      selector: .jp-CodeCell
      styles:
        '&[jp-fonts-cell-tags*=",remove-inputs,"] .jp-InputArea':
          display: none
```
